// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: other_messages.proto

package cases_custom

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
other_package_custom "github.com/envoyproxy/protoc-gen-validate/tests/harness/cases_custom/other_package_custom/go"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TestMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Const  string   `protobuf:"bytes,1,opt,name=const,proto3" json:"const,omitempty"`
	Nested *TestMsg `protobuf:"bytes,2,opt,name=nested,proto3" json:"nested,omitempty"`
}

func (x *TestMsg) Reset() {
	*x = TestMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_other_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMsg) ProtoMessage() {}

func (x *TestMsg) ProtoReflect() protoreflect.Message {
	mi := &file_other_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMsg.ProtoReflect.Descriptor instead.
func (*TestMsg) Descriptor() ([]byte, []int) {
	return file_other_messages_proto_rawDescGZIP(), []int{0}
}

func (x *TestMsg) GetConst() string {
	if x != nil {
		return x.Const
	}
	return ""
}

func (x *TestMsg) GetNested() *TestMsg {
	if x != nil {
		return x.Nested
	}
	return nil
}

type MessageNone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val *MessageNone_NoneMsg `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *MessageNone) Reset() {
	*x = MessageNone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_other_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageNone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageNone) ProtoMessage() {}

func (x *MessageNone) ProtoReflect() protoreflect.Message {
	mi := &file_other_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageNone.ProtoReflect.Descriptor instead.
func (*MessageNone) Descriptor() ([]byte, []int) {
	return file_other_messages_proto_rawDescGZIP(), []int{1}
}

func (x *MessageNone) GetVal() *MessageNone_NoneMsg {
	if x != nil {
		return x.Val
	}
	return nil
}

type MessageDisabled struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val uint64 `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *MessageDisabled) Reset() {
	*x = MessageDisabled{}
	if protoimpl.UnsafeEnabled {
		mi := &file_other_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageDisabled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDisabled) ProtoMessage() {}

func (x *MessageDisabled) ProtoReflect() protoreflect.Message {
	mi := &file_other_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDisabled.ProtoReflect.Descriptor instead.
func (*MessageDisabled) Descriptor() ([]byte, []int) {
	return file_other_messages_proto_rawDescGZIP(), []int{2}
}

func (x *MessageDisabled) GetVal() uint64 {
	if x != nil {
		return x.Val
	}
	return 0
}

type MessageIgnored struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val uint64 `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *MessageIgnored) Reset() {
	*x = MessageIgnored{}
	if protoimpl.UnsafeEnabled {
		mi := &file_other_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageIgnored) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageIgnored) ProtoMessage() {}

func (x *MessageIgnored) ProtoReflect() protoreflect.Message {
	mi := &file_other_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageIgnored.ProtoReflect.Descriptor instead.
func (*MessageIgnored) Descriptor() ([]byte, []int) {
	return file_other_messages_proto_rawDescGZIP(), []int{3}
}

func (x *MessageIgnored) GetVal() uint64 {
	if x != nil {
		return x.Val
	}
	return 0
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val *TestMsg `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_other_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_other_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_other_messages_proto_rawDescGZIP(), []int{4}
}

func (x *Message) GetVal() *TestMsg {
	if x != nil {
		return x.Val
	}
	return nil
}

type MessageCrossPackage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val *other_package_custom.Embed `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *MessageCrossPackage) Reset() {
	*x = MessageCrossPackage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_other_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageCrossPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageCrossPackage) ProtoMessage() {}

func (x *MessageCrossPackage) ProtoReflect() protoreflect.Message {
	mi := &file_other_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageCrossPackage.ProtoReflect.Descriptor instead.
func (*MessageCrossPackage) Descriptor() ([]byte, []int) {
	return file_other_messages_proto_rawDescGZIP(), []int{5}
}

func (x *MessageCrossPackage) GetVal() *other_package_custom.Embed {
	if x != nil {
		return x.Val
	}
	return nil
}

type MessageSkip struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val *TestMsg `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *MessageSkip) Reset() {
	*x = MessageSkip{}
	if protoimpl.UnsafeEnabled {
		mi := &file_other_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageSkip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSkip) ProtoMessage() {}

func (x *MessageSkip) ProtoReflect() protoreflect.Message {
	mi := &file_other_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSkip.ProtoReflect.Descriptor instead.
func (*MessageSkip) Descriptor() ([]byte, []int) {
	return file_other_messages_proto_rawDescGZIP(), []int{6}
}

func (x *MessageSkip) GetVal() *TestMsg {
	if x != nil {
		return x.Val
	}
	return nil
}

type MessageRequired struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val *TestMsg `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *MessageRequired) Reset() {
	*x = MessageRequired{}
	if protoimpl.UnsafeEnabled {
		mi := &file_other_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageRequired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRequired) ProtoMessage() {}

func (x *MessageRequired) ProtoReflect() protoreflect.Message {
	mi := &file_other_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRequired.ProtoReflect.Descriptor instead.
func (*MessageRequired) Descriptor() ([]byte, []int) {
	return file_other_messages_proto_rawDescGZIP(), []int{7}
}

func (x *MessageRequired) GetVal() *TestMsg {
	if x != nil {
		return x.Val
	}
	return nil
}

type MessageWith3DInside struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MessageWith3DInside) Reset() {
	*x = MessageWith3DInside{}
	if protoimpl.UnsafeEnabled {
		mi := &file_other_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageWith3DInside) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWith3DInside) ProtoMessage() {}

func (x *MessageWith3DInside) ProtoReflect() protoreflect.Message {
	mi := &file_other_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWith3DInside.ProtoReflect.Descriptor instead.
func (*MessageWith3DInside) Descriptor() ([]byte, []int) {
	return file_other_messages_proto_rawDescGZIP(), []int{8}
}

type MessageNone_NoneMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MessageNone_NoneMsg) Reset() {
	*x = MessageNone_NoneMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_other_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageNone_NoneMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageNone_NoneMsg) ProtoMessage() {}

func (x *MessageNone_NoneMsg) ProtoReflect() protoreflect.Message {
	mi := &file_other_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageNone_NoneMsg.ProtoReflect.Descriptor instead.
func (*MessageNone_NoneMsg) Descriptor() ([]byte, []int) {
	return file_other_messages_proto_rawDescGZIP(), []int{1, 0}
}

var File_other_messages_proto protoreflect.FileDescriptor

var file_other_messages_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x68, 0x61,
	0x72, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x63, 0x61, 0x73, 0x65, 0x73, 0x5f, 0x63, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x1a, 0x41, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x68, 0x61, 0x72, 0x6e, 0x65, 0x73,
	0x73, 0x2f, 0x63, 0x61, 0x73, 0x65, 0x73, 0x5f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x2f, 0x6f,
	0x74, 0x68, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x2f, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x68,
	0x0a, 0x07, 0x54, 0x65, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x20, 0x0a, 0x05, 0x63, 0x6f, 0x6e,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0xfa, 0x42, 0x07, 0x72, 0x05, 0x0a,
	0x03, 0x66, 0x6f, 0x6f, 0x52, 0x05, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x06, 0x6e,
	0x65, 0x73, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x73, 0x2e, 0x68, 0x61, 0x72, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x63, 0x61, 0x73, 0x65,
	0x73, 0x5f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x4d, 0x73, 0x67,
	0x52, 0x06, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x22, 0x5b, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x4e, 0x6f, 0x6e, 0x65, 0x12, 0x41, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x68, 0x61, 0x72,
	0x6e, 0x65, 0x73, 0x73, 0x2e, 0x63, 0x61, 0x73, 0x65, 0x73, 0x5f, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x6e, 0x65, 0x2e, 0x4e, 0x6f,
	0x6e, 0x65, 0x4d, 0x73, 0x67, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x1a, 0x09, 0x0a, 0x07, 0x4e, 0x6f,
	0x6e, 0x65, 0x4d, 0x73, 0x67, 0x22, 0x31, 0x0a, 0x0f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x19, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x20, 0x7b, 0x52, 0x03,
	0x76, 0x61, 0x6c, 0x3a, 0x03, 0xf8, 0x42, 0x01, 0x22, 0x30, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x49, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x64, 0x12, 0x19, 0x0a, 0x03, 0x76, 0x61,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x20, 0x7b,
	0x52, 0x03, 0x76, 0x61, 0x6c, 0x3a, 0x03, 0x80, 0x43, 0x01, 0x22, 0x40, 0x0a, 0x07, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x35, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x23, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x68, 0x61, 0x72, 0x6e, 0x65,
	0x73, 0x73, 0x2e, 0x63, 0x61, 0x73, 0x65, 0x73, 0x5f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x2e,
	0x54, 0x65, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x5f, 0x0a, 0x13,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x72, 0x6f, 0x73, 0x73, 0x50, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x12, 0x48, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x36, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x68, 0x61, 0x72, 0x6e, 0x65, 0x73, 0x73,
	0x2e, 0x63, 0x61, 0x73, 0x65, 0x73, 0x5f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x2e, 0x6f, 0x74,
	0x68, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x2e, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x4e, 0x0a,
	0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x6b, 0x69, 0x70, 0x12, 0x3f, 0x0a, 0x03,
	0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x73, 0x2e, 0x68, 0x61, 0x72, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x63, 0x61, 0x73, 0x65, 0x73, 0x5f,
	0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x42, 0x08,
	0xfa, 0x42, 0x05, 0x8a, 0x01, 0x02, 0x08, 0x01, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x52, 0x0a,
	0x0f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64,
	0x12, 0x3f, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x74, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x68, 0x61, 0x72, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x63, 0x61,
	0x73, 0x65, 0x73, 0x5f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x4d,
	0x73, 0x67, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x8a, 0x01, 0x02, 0x10, 0x01, 0x52, 0x03, 0x76, 0x61,
	0x6c, 0x22, 0x15, 0x0a, 0x13, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x57, 0x69, 0x74, 0x68,
	0x33, 0x64, 0x49, 0x6e, 0x73, 0x69, 0x64, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x63, 0x61, 0x73, 0x65,
	0x73, 0x5f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_other_messages_proto_rawDescOnce sync.Once
	file_other_messages_proto_rawDescData = file_other_messages_proto_rawDesc
)

func file_other_messages_proto_rawDescGZIP() []byte {
	file_other_messages_proto_rawDescOnce.Do(func() {
		file_other_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_other_messages_proto_rawDescData)
	})
	return file_other_messages_proto_rawDescData
}

var file_other_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_other_messages_proto_goTypes = []interface{}{
	(*TestMsg)(nil),                    // 0: tests.harness.cases_custom.TestMsg
	(*MessageNone)(nil),                // 1: tests.harness.cases_custom.MessageNone
	(*MessageDisabled)(nil),            // 2: tests.harness.cases_custom.MessageDisabled
	(*MessageIgnored)(nil),             // 3: tests.harness.cases_custom.MessageIgnored
	(*Message)(nil),                    // 4: tests.harness.cases_custom.Message
	(*MessageCrossPackage)(nil),        // 5: tests.harness.cases_custom.MessageCrossPackage
	(*MessageSkip)(nil),                // 6: tests.harness.cases_custom.MessageSkip
	(*MessageRequired)(nil),            // 7: tests.harness.cases_custom.MessageRequired
	(*MessageWith3DInside)(nil),        // 8: tests.harness.cases_custom.MessageWith3dInside
	(*MessageNone_NoneMsg)(nil),        // 9: tests.harness.cases_custom.MessageNone.NoneMsg
	(*other_package_custom.Embed)(nil), // 10: tests.harness.cases_custom.other_package_custom.Embed
}
var file_other_messages_proto_depIdxs = []int32{
	0,  // 0: tests.harness.cases_custom.TestMsg.nested:type_name -> tests.harness.cases_custom.TestMsg
	9,  // 1: tests.harness.cases_custom.MessageNone.val:type_name -> tests.harness.cases_custom.MessageNone.NoneMsg
	0,  // 2: tests.harness.cases_custom.Message.val:type_name -> tests.harness.cases_custom.TestMsg
	10, // 3: tests.harness.cases_custom.MessageCrossPackage.val:type_name -> tests.harness.cases_custom.other_package_custom.Embed
	0,  // 4: tests.harness.cases_custom.MessageSkip.val:type_name -> tests.harness.cases_custom.TestMsg
	0,  // 5: tests.harness.cases_custom.MessageRequired.val:type_name -> tests.harness.cases_custom.TestMsg
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_other_messages_proto_init() }
func file_other_messages_proto_init() {
	if File_other_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_other_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_other_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageNone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_other_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageDisabled); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_other_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageIgnored); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_other_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_other_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageCrossPackage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_other_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageSkip); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_other_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageRequired); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_other_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageWith3DInside); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_other_messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageNone_NoneMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_other_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_other_messages_proto_goTypes,
		DependencyIndexes: file_other_messages_proto_depIdxs,
		MessageInfos:      file_other_messages_proto_msgTypes,
	}.Build()
	File_other_messages_proto = out.File
	file_other_messages_proto_rawDesc = nil
	file_other_messages_proto_goTypes = nil
	file_other_messages_proto_depIdxs = nil
}
