// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: other_bool.proto

package cases_custom

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _other_bool_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on BoolNone with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *BoolNone) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Val

	return nil
}

// BoolNoneValidationError is the validation error returned by
// BoolNone.Validate if the designated constraints aren't met.
type BoolNoneValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BoolNoneValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BoolNoneValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BoolNoneValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BoolNoneValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BoolNoneValidationError) ErrorName() string { return "BoolNoneValidationError" }

// Error satisfies the builtin error interface
func (e BoolNoneValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBoolNone.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BoolNoneValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BoolNoneValidationError{}

// Validate checks the field values on BoolConstTrue with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *BoolConstTrue) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetVal() != true {
		return BoolConstTrueValidationError{
			field:  "Val",
			reason: "value must equal true",
		}
	}

	return nil
}

// BoolConstTrueValidationError is the validation error returned by
// BoolConstTrue.Validate if the designated constraints aren't met.
type BoolConstTrueValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BoolConstTrueValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BoolConstTrueValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BoolConstTrueValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BoolConstTrueValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BoolConstTrueValidationError) ErrorName() string { return "BoolConstTrueValidationError" }

// Error satisfies the builtin error interface
func (e BoolConstTrueValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBoolConstTrue.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BoolConstTrueValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BoolConstTrueValidationError{}

// Validate checks the field values on BoolConstFalse with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *BoolConstFalse) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetVal() != false {
		return BoolConstFalseValidationError{
			field:  "Val",
			reason: "value must equal false",
		}
	}

	return nil
}

// BoolConstFalseValidationError is the validation error returned by
// BoolConstFalse.Validate if the designated constraints aren't met.
type BoolConstFalseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BoolConstFalseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BoolConstFalseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BoolConstFalseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BoolConstFalseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BoolConstFalseValidationError) ErrorName() string { return "BoolConstFalseValidationError" }

// Error satisfies the builtin error interface
func (e BoolConstFalseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBoolConstFalse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BoolConstFalseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BoolConstFalseValidationError{}
